### PR TITLE
Cleaned up build system

### PR DESCRIPTION
**Pull request by Ericson2314**
Finally!

 - Packages live in `(import ./env.nix).unisonPackages.<ghcjs|ghc7101>.<name>`.
 - nix-shell in shared and editor works like `nix-shell -A <ghcjs|ghc7101>`.
 - package `default.nix`s are exactly what `cabal2nix` generated.
 - No submodules, all dependencies are downloaded via Nix.
 - No wrapper scripts needed, though the upstream try-reflex wrapper script can optionally used (as always) to aid in installing nix.

Tested on mac. Shared builds with both compiles, editor builds with ghcjs (no ghc + reflex on mac), and node doesn't build (dep unix-time fails during build, don't see how this could be fault of these changes).

### CODE REVIEW

**Comment by pchiusano** [comment]
Wow awesome! Will review shortly.

**Comment by pchiusano** [comment]
Great, merging... one question - do we know if we need to move version constraints into the .cabal files, or if it will pick up the cabal.config?

**Comment by pchiusano** [comment]
Hmm, I get the following error on OSX - 

```
$ cd editor
$ nix-shell
... lots of logging output, stuff being downloaded
... and then:
error: Package ‘at-spi2-atk-2.12.1’ in ‘/nix/store/mi8f1qi5rsy3i2vfs5bdd76mx0rwxhqr-nixpkgs-7f7dbb7c36b0f636f82a25722ebb2e89b43a69b1-src/pkgs/development/libraries/at-spi2-atk/default.nix:8’ is not supported on ‘x86_64-darwin’, refusing to evaluate.
For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.
For `nix-env` you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.
```

Any idea what this is?

**Comment by pchiusano** [comment]
@Ericson2314 Based on the log output, it looks to me like nix is not picking up the cabal.config file, so it's attempting to use the latest version of everything and running into errors:

```
Dependency network -any: using network-2.6.0.2
Dependency unix -any: using unix-2.7.1.0
...
```

This might be a silly question, but can you explain how `nix-shell` is selecting a version of the Haskell packages used? Like, `default.nix` doesn't mention version numbers, the dependencies are all parameters to the derivation. So there has to be some place where those dependencies are bound right? Where is that?

**Comment by Ericson2314** [comment]
Yeah Nix has to SMT solver or anything like that. The package sets just have one version of each package, and you are stuck with what's passed in. If you look at https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/development/haskell-modules/hackage-packages.nix you can see that occasionally there a multiple versions (`<name>_v_v_v_v`), but those are presumably just included by some shortlist peti throws at cabal2nix when it scraps package.

Since Nix is thus more geared about curating package versions that work together, as opposed to the open-world version reconciliation that cabal does, it would be nice if Nix had package sets for those LTS versions. IMO Nix > Stackage, but the LTS curated versions are nice idea that fits Nix perfectly.

**Comment by pchiusano** [comment]
@Ericson2314 hmm, so there is no guarantee that the Haskell packages in Nix even build together? How is this working on your machine but not mine, I wonder? Can you show the terminal session with the exact commands you are using to build `shared`, `node`, and `editor`? Maybe I am doing something differently.

It is nice that in principle Nix lets you create curated sets of packages, but if no one is doing that for the Haskell Nix packages, then I don't get why people are so excited about using Nix for Haskell development. Aside from saving on some compilation time, it seems we are worse off than just using cabal sandboxes with the versions pinned in the Stackage-curated `cabal.config` files. That at least is reproducible, and everything has been tested to work with each other.

Am I misunderstanding things here?

**Comment by Ericson2314** [comment]
Sorry, I didn't take too close a look at your first comment. `cd editor; nix-shell -A ghcjs` will work on mac. The problem is reflex + normal ghc requires gtk.

Regarding nix in general, the build jobs on hydra provide some compatibility. Also by using a specific commit of nixpkgs we get reproducibility. And not only can we use the LTS versions, we also have the tools to do the same testing to discover the compatible versions. I'd say the same people most excited about Nix are also annoyed that there are so many things we know how to do, but aren't doing due to a lack of (people + cpu) * time.

**Comment by pchiusano** [comment]
Ah, okay, thanks for the reply, will try that, going to be away from my
computer for the evening though. I have some more general nix questions but
I'll try to catch you on Gitter at some point. :)

**Pull request merged**
