### PR TITLE
Copy-paste friendly README.md commands

### PR DESCRIPTION
**Pull request by CGenie**

### CODE REVIEW

**Comment by int-index** [comment]
1. Copy-pasting terminal commands is bad.
2. Now you can't visually differentiate input and output.

**Comment by kirbyfan64** [comment]
> Copy-pasting terminal commands is bad.

It's fine provided you actually *read* the commands you're copying.

**Comment by CGenie** [comment]
Well, I prefer reading first too and then copying and pasting. Plus this commit makes commands in README uniform:

https://github.com/unisonweb/platform/pull/29/files#diff-04c6e90faac2675aa89e2176d2eec7d8R73

**Comment by pchiusano** [comment]
Thanks for the PR, but I don't want to accept this. The leading `$` or `>` is a pretty common convention that makes it clear what is terminal input and what is output (if that were unclear to anyone, I'd rather clarify that notational convention as a parenthetical just before or after the first example).

And I don't think copy-pasting is that hard if you want to do that, just skip the prompt character. :)

**Pull request closed without merging**
