### PR TITLE
Convert build to use stack

### PR DESCRIPTION
**Pull request by pchiusano**
I deleted all the old nix stuff and updated the README and the Vagrant setup. The overall setup is much simpler, and everything seems to work great. I believe it would now be trivial to have a Travis job for the project, but I haven't tried to hooking that up.

### CODE REVIEW

**Comment by joshcough** [comment]
Oh you abandoned nix altogether?

**Comment by joshcough** [comment]
I had Travis working with Stack here: https://github.com/joshcough/Scrabble, but do get intermittent build errors for reasons I haven't figured out yet. The stack documentation for Travis is really easy, too.

**Comment by pchiusano** [comment]
Yup. I was never a big fan of Nix, but for a while it seemed to be the only way to use Reflex with GHCJS. Now that there's [this example for using Stack](https://github.com/luigy/try-stack-reflex), I didn't see any point in sticking with Nix.

**Comment by joshcough** [comment]
Hmm. I remember you claiming to be a big fan of it for a while :) But, I'm glad to see you decided not to use it, because I was about to try to copy your example!

**Comment by pchiusano** [comment]
Ha, you can't trust anything I say obviously. :) I do still like the general idea of Nix quite a bit (and Unison uses some of those same ideas). But the devil is in the details.

**Comment by Ericson2314** [comment]
Yeah, not going to lie the old state of things was not Nix at its finest. I am trying out some things in at https://github.com/forked-upstream-packages-for-ghcjs and https://github.com/Ericson2314/nixpkgs/tree/ghcjs which will hopefully improve the state of ghcjs for Nix and Stack alike---`ghcjs-boot` is terrifying, and the `try-reflex-stack` doesn't solve the problem of ghcjs and ghc library versions not quite aligning.

**Comment by pchiusano** [comment]
@Ericson2314 cool. The warnings about ghc library versions not aligning are kind of janky I agree. But it does still work okay and the setup is very simple so I'm not complaining. :)

**Pull request merged**
